#ifndef BANKACCOUNTMAIN_GLOBAL_H
#define BANKACCOUNTMAIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BANKACCOUNTMAIN_LIBRARY)
#define BANKACCOUNTMAIN_EXPORT Q_DECL_EXPORT
#else
#define BANKACCOUNTMAIN_EXPORT Q_DECL_IMPORT
#endif

#endif // BANKACCOUNTMAIN_GLOBAL_H
